# Generated by Django 6.0.6 on 2026-06-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship'), ('Remote', 'Remote')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=150),
        ),
    ]
